# Generated by Django 4.1.2 on 2022-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_studentinfo_teacherinfo_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
