# Generated by Django 4.1.2 on 2022-10-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_course_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_department',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_pc',
            field=models.CharField(blank=True, default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_total',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
